name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@ec2-13-233-38-68.ap-south-1.compute.amazonaws.com 'bash -s' < deploy.sh
